UC create routine / CRUD exercises necesary code
AgustinStringa/tp-dsw-backendapp pull request #23
Opened 2024-09-24 03:46 UTC by AgustinStringa

2024-09-24 14:37 UTC, AaronDeBernardo requested changes

2024-09-24 14:37 UTC, AaronDeBernardo commented on src/Routine/CreateRoutine.controller.ts
>  const createRoutineController = {
Es posible optimizarlo, realizando todo en una consulta con el orm

2024-09-24 14:37 UTC, AaronDeBernardo commented on src/Routine/Routine.controller.ts
Las validaciones de las líneas 51 a 61 se pueden ahorrar al asignar en el backend las fechas de inicio y de fin. En el front no está mal calcularlas, pero solo sirven para mostrarle al usuario, no es necesario enviarlas en la petición.

2024-09-24 14:37 UTC, AaronDeBernardo commented on src/Routine/Routine.controller.ts
Al usar findOneOrFail() para buscar al cliente y al entrendor (líneas 62 y 68) en el caso de no encontrarlo, se ejecuta el bloque catch, ya que "Fail". Por lo tanto, los if de líneas 63 y 69 no se usan nunca.
Por otra parte, si se quiere devolver un mensaje acorde de error, hay que analizar el fallo en el catch.

2024-09-24 14:37 UTC, AaronDeBernardo commented on src/Routine/Routine.controller.ts
> +      //TO DO: HABRIA Q REVISAR SI ALGUNA DE TODAS COINCIDE
no entiendo esto

2024-09-24 14:37 UTC, AaronDeBernardo commented on src/Routine/Routine.controller.ts
> +                start: { $lt: new Date(req.body.end) },
Acordate que siempre usamos startOfDay()
Te olvidaste de convertir la fecha al inicio para guardarlo, y también para compararlo. Se puede hacer en la función sanitizadora.

2024-09-24 14:37 UTC, AaronDeBernardo commented on src/Routine/Routine.controller.ts
> +      const today = startOfDay(new Date());
declarada pero no usada

2024-09-24 14:37 UTC, AaronDeBernardo commented on src/Routine/Routine.controller.ts
> +                start: { $lt: new Date(req.body.end) },
Siempre van a haber rutinas con fechas de inicio previas a la de la nueva rutina.

2024-09-25 13:37 UTC, AaronDeBernardo commented on src/Routine/Routine.controller.ts
> +      start: startOfDay(req.body.start),
me queda la duda que pasa si se envía un valor que hace fallar a la función startOfDay

2024-10-04 00:34 UTC, AgustinStringa commented on src/Routine/Routine.controller.ts
> +      start: startOfDay(req.body.start),
> me queda la duda que pasa si se envía un valor que hace fallar a la función startOfDay

si es un dato no date -> responde bad request

2024-10-04 00:36 UTC, merged